"""
Tool handler: generate_prompt — autonomous system prompt generation.

Uses a meta-prompt to ask Claude to generate a specialized system prompt
for an existing agent. The generated prompt gets stored in the agent's
AgentDefinition and optionally as a PromptVersion for audit trail.

This is a separate Claude API call (not the calling agent's conversation) —
the meta-prompt is crafted to produce high-quality system prompts.
"""

import logging

from sqlalchemy import select

from app.agents.models import Agent, AgentDefinition
from app.workers.tool_registry import ToolContext, register_tool

logger = logging.getLogger(__name__)

# Meta-prompt that instructs Claude to generate a specialized system prompt
_META_PROMPT = """Eres un Prompt Engineer experto. Tu tarea es crear un system prompt
altamente especializado para un agente de IA que trabaja en una empresa.

El prompt que generes debe:
1. Definir claramente el rol, responsabilidades y personalidad del agente
2. Incluir las capacidades específicas que el agente debe demostrar
3. Establecer el tono y estilo de comunicación (profesional pero accesible)
4. Incluir guardrails de seguridad (no inventar datos, pedir clarificación si falta info)
5. Estar en español ya que los usuarios de la empresa hablan español
6. Ser conciso pero completo (máximo 500 palabras)

Responde SOLO con el system prompt, sin explicaciones adicionales ni markdown de código."""


@register_tool("generate_prompt")
async def handle_generate_prompt(ctx: ToolContext, tool_input: dict) -> dict:
    """Generate a specialized system prompt for an agent using a meta-prompt."""
    agent_slug = tool_input.get("agent_slug")
    role_description = tool_input.get("role_description", "")
    capabilities = tool_input.get("capabilities", [])

    if not agent_slug:
        return {"error": "agent_slug is required"}

    # Look up the target agent by slug
    result = await ctx.db.execute(
        select(Agent).where(
            Agent.slug == agent_slug,
            Agent.organization_id == ctx.org_id,
        )
    )
    agent = result.scalar_one_or_none()
    if agent is None:
        return {"error": f"Agent '{agent_slug}' not found"}

    # Load agent definition
    defn_result = await ctx.db.execute(
        select(AgentDefinition).where(AgentDefinition.agent_id == agent.id)
    )
    definition = defn_result.scalar_one_or_none()
    if definition is None:
        return {"error": f"Agent '{agent_slug}' has no definition (not an internal agent)"}

    # Build the generation request
    caps_text = ", ".join(capabilities) if capabilities else "generales"
    user_message = (
        f"Genera un system prompt para el siguiente agente:\n\n"
        f"**Nombre:** {agent.name}\n"
        f"**Descripción del rol:** {role_description or agent.description or 'Sin descripción'}\n"
        f"**Capacidades requeridas:** {caps_text}\n"
        f"**Departamento:** {agent.department_id or 'No asignado'}\n\n"
        f"El agente trabaja en una agencia digital que ofrece servicios de marketing, "
        f"contenido, desarrollo y automatización."
    )

    # Make a separate Claude call to generate the prompt
    # Lazy import to avoid circular dependency (agent_executor → tools → generate_prompt → agent_executor)
    from app.workers.agent_executor import _call_claude_with_retry, _get_client

    try:
        client = _get_client()
        response = await _call_claude_with_retry(
            client,
            model="claude-sonnet-4-20250514",
            max_tokens=2048,
            temperature=0.6,  # some creativity but mostly consistent
            system=_META_PROMPT,
            messages=[{"role": "user", "content": user_message}],
        )
    except Exception as exc:
        return {"error": f"Claude API call for prompt generation failed: {str(exc)[:200]}"}

    # Extract the generated prompt
    generated_prompt = ""
    for block in response.content:
        if block.type == "text":
            generated_prompt += block.text

    if not generated_prompt.strip():
        return {"error": "Claude returned empty prompt"}

    # Update the agent's definition with the new prompt
    definition.system_prompt = generated_prompt.strip()
    await ctx.db.flush()

    # Create a PromptVersion for audit trail
    try:
        from app.prompts.service import PromptService
        prompt_service = PromptService(ctx.db)
        from app.prompts.schemas import PromptVersionCreate
        await prompt_service.create_version(
            agent_id=agent.id,
            data=PromptVersionCreate(
                system_prompt=generated_prompt.strip(),
                model_name=definition.model_name,
                temperature=float(definition.temperature),
                max_tokens=definition.max_tokens,
                change_notes=f"Auto-generated by {ctx.calling_agent_name}",
                created_by=ctx.calling_agent_name,
            ),
        )
    except Exception as exc:
        # Non-fatal — the prompt is already saved in the definition
        logger.warning("Failed to create PromptVersion for audit trail: %s", exc)

    return {
        "success": True,
        "agent_slug": agent_slug,
        "prompt_preview": generated_prompt[:300] + ("..." if len(generated_prompt) > 300 else ""),
        "prompt_length": len(generated_prompt),
        "tokens_used": response.usage.input_tokens + response.usage.output_tokens,
    }
