"""make_role_department_nullable

Revision ID: 7cf92d97cd85
Revises: fa1356ecb1a6
Create Date: 2026-03-29 15:01:58.561494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf92d97cd85'
down_revision: Union[str, None] = 'fa1356ecb1a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'role_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('agents', 'department_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'department_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('agents', 'role_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
