"""add_agent_lifecycle_and_notifications

Revision ID: b0fd71897093
Revises: b9fbcf6fb0c4
Create Date: 2026-04-12 00:28:36.707179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0fd71897093'
down_revision: Union[str, None] = 'b9fbcf6fb0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('notification_type', sa.Enum('AGENT_IDLE', 'AGENT_CREATED', 'DEPARTMENT_CREATED', 'TASK_ASSIGNED', 'PROMPT_GENERATED', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.add_column('agents', sa.Column('last_task_completed_at', sa.DateTime(), nullable=True))
    op.add_column('agents', sa.Column('total_tasks_completed', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('created_by_agent_id', sa.UUID(), nullable=True))
    op.add_column('agents', sa.Column('creation_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'agents', 'agents', ['created_by_agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'creation_reason')
    op.drop_column('agents', 'created_by_agent_id')
    op.drop_column('agents', 'total_tasks_completed')
    op.drop_column('agents', 'last_task_completed_at')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
