"""add credentials table

Revision ID: b9fbcf6fb0c4
Revises: a3f892bc1d47
Create Date: 2026-04-11 16:45:17.458705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9fbcf6fb0c4'
down_revision: Union[str, None] = 'a3f892bc1d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('credential_type', sa.Enum('API_KEY', 'OAUTH_TOKEN', 'BEARER_TOKEN', 'BASIC_AUTH', 'CUSTOM', name='credentialtype'), nullable=False),
    sa.Column('secret_value', sa.Text(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('secret_preview', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_agent_id'), 'credentials', ['agent_id'], unique=False)
    op.create_index(op.f('ix_credentials_organization_id'), 'credentials', ['organization_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_organization_id'), 'knowledge_chunks', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunks_organization_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_credentials_organization_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_agent_id'), table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
