export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/",
  AGENTS: "/agents",
  AGENT_DETAIL: "/agents/:id",
  AGENT_CREATE: "/agents/new",
  AGENT_REGISTER: "/agents/register",
  ORG_CHART: "/org-chart",
  DEPARTMENTS: "/departments",
  DEPARTMENT_DETAIL: "/departments/:id",
  TASKS: "/tasks",
  TASK_CREATE: "/tasks/new",
  TASK_DETAIL: "/tasks/:id",
  CEO: "/ceo",
  ACTIVITIES: "/activities",
  METRICS: "/metrics",
  INTERACTIONS: "/interactions",
  IMPROVEMENTS: "/improvements",
  PROMPTS: "/prompts",
  INTEGRATIONS: "/integrations",
  KNOWLEDGE: "/knowledge",
  CREDENTIALS: "/credentials",
} as const;
